### ISSUE TITLE
yarn install failing with node 14.5

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sample-app-mobile#52]
With node 14.5 I was getting the following errors when running `yarn install`. Downgraded to node LTS and it worked just fine

```
5 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/14.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command \"/usr/local/Cellar/node/14.5.0/bin/node\" \"/usr/local/Cellar/node/14.5.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\" \"--release\"
gyp ERR! cwd /Users/nikolayadvolodkin/Documents/source/sample-app-mobile/node_modules/fibers
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
```

**Comment by wswebcreation** [comment]
Hi @nadvolod 

Looks like WDIO is not supported here with NodeJS 14.
Need to dive into this but because you have a workaround and I'll be on PTO soon it will be around the second week of August

**Comment by nadvolod** [comment]
@wswebcreation no worries man :) take your time. I just wanted to log it.

**Comment by wswebcreation** [comment]
@nadvolod 

WebdriverIO V5 and V6 don't support NodeJS 14 yet, that's why you got the issue. When you use NVM you can easily switch to 12 which works fine

**Comment by wswebcreation** [comment]
ok, found the issue, it's not related to WebdriverIO. It's related to an image compare module which is used. I'll remove it for now and then you can use it

**Comment by wswebcreation** [comment]
@nikolay-advolodkin 

This should be solved now with the latest version
